Chore: Update workfflows from osc-transformer-presteps
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -18,7 +18,7 @@ jobs:
   repository:
     name: "Repository"
     # yamllint disable-line rule:line-length
-    uses: os-climate/osc-github-devops/.github/workflows/reuse-inspect-repository.yaml@e40c93a51cc32cbddd4767a75e2209af971df9e0 # 2025-02-25
+    uses: os-climate/osc-github-devops/.github/workflows/reuse-inspect-repository.yaml@45cee44c1a0bfdc8e64f94cf32c833ef61f95a50 # 2025-02-25
     permissions:
       contents: read
 
@@ -42,7 +42,7 @@ jobs:
         - name: "Build Python project"
           id: python-build
           # yamllint disable-line rule:line-length
-          uses: os-climate/osc-github-devops/.github/actions/python-build-action@e40c93a51cc32cbddd4767a75e2209af971df9e0 # 2025-02-25
+          uses: os-climate/osc-github-devops/.github/actions/python-build-action@45cee44c1a0bfdc8e64f94cf32c833ef61f95a50 # 2025-02-25
           with:
             tag: ${{ needs.repository.outputs.build_tag }}
             attestations: "true"
@@ -51,7 +51,7 @@ jobs:
   python-test:
     name: "Test"
     # yamllint disable-line rule:line-length
-    uses: os-climate/osc-github-devops/.github/workflows/reuse-python-tests.yaml@e40c93a51cc32cbddd4767a75e2209af971df9e0 # 2025-02-25
+    uses: os-climate/osc-github-devops/.github/workflows/reuse-python-tests.yaml@45cee44c1a0bfdc8e64f94cf32c833ef61f95a50 # 2025-02-25
     needs:
       - repository
       - python-build
@@ -67,7 +67,7 @@ jobs:
   python-audit:
     name: "Audit"
     # yamllint disable-line rule:line-length
-    uses: os-climate/osc-github-devops/.github/workflows/reuse-python-audit.yaml@e40c93a51cc32cbddd4767a75e2209af971df9e0 # 2025-02-25
+    uses: os-climate/osc-github-devops/.github/workflows/reuse-python-audit.yaml@45cee44c1a0bfdc8e64f94cf32c833ef61f95a50 # 2025-02-25
     needs:
       - repository
       - python-build
@@ -84,7 +84,7 @@ jobs:
     name: "Notebooks"
     if: needs.repository.outputs.jupyter_notebooks  == 'true'
     # yamllint disable-line rule:line-length
-    uses: os-climate/osc-github-devops/.github/workflows/reuse-notebook-tests.yaml@e40c93a51cc32cbddd4767a75e2209af971df9e0 # 2025-02-25
+    uses: os-climate/osc-github-devops/.github/workflows/reuse-notebook-tests.yaml@45cee44c1a0bfdc8e64f94cf32c833ef61f95a50 # 2025-02-25
     needs:
       - repository
       - python-build
@@ -114,54 +114,106 @@ jobs:
     # Note: environment must be specified at BOTH job level, and input to publish action
     environment: development
     steps:
+      # Need repository content to extract project name
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: "Test Package Publishing"
+      - name: "Extract project/repository naming"
+        id: naming
         # yamllint disable-line rule:line-length
-        uses: ./.github/actions/pypi-publish-action # Local copy of upstream 2025-02-25
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        uses: lfit/releng-reusable-workflows/.github/actions/python-project-name-action@431c4e424c15544f98ec1321f6668f655c238d3a # 2025-02-10
+
+      - name: "⬇ Download build artefacts"
+        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
         with:
-          environment: development
-          tag: ${{ needs.repository.outputs.build_tag }}
-          # yamllint disable-line rule:line-length
-          one_password_item: "op://hdiyadcjno2knqgvcy4wj5ulya/tm2ffuusrynfivtcsnamginhm4/password"
-          op_service_account_token: ${{ secrets.ONE_PASSWORD_PRODUCTION }}
-          pypi_credential: ${{ secrets.PYPI_PRODUCTION }}
-          attestations: "true"
+          name: ${{ steps.naming.outputs.python_project_name }}
+          path: "dist"
+
+      - name: "Remove unsupported artefact file types"
+        shell: bash
+        run: |
+          # Remove unsupported artefact file types
+          find . ! -name '*.whl' ! -name '*.tar.gz' -type f -exec rm -f {} + || true
+
+      - name: "Checking package index for build/release"
+        id: check-remote
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/pypi-version-check-action@50987892d52819798d74f5b381d3abfb8d54cbf0 # 2025-03-03
+        with:
+          index_url: https://test.pypi.org/simple
+          package_name: ${{ steps.naming.outputs.python_project_name }}
+          package_version: ${{ needs.repository.outputs.build_tag }}
+          environment: "development"
+
+      - name: "Publish PyPI [Trusted Publishing]"
+        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
+        # yamllint disable-line rule:line-length
+        with:
+          repository-url: https://test.pypi.org/legacy/
+          # We already validated earlier in the pipeline (twine)
+          verify-metadata: false
+          attestations: true
+          # Show checksum values
+          print-hash: true
+          # Optional debugging, pretty much essential for information on failures
+          verbose: true
 
   pypi-release:
-          name: "PyPI release"
-          # yamllint disable-line rule:line-length
-          if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[release]')
-          needs:
-            - repository
-            - pypi-test
-          runs-on: "ubuntu-24.04"
-          permissions:
-            contents: read
-            # Needed for trusted publishing; must also be passed from parent workflows
-            id-token: write
-          env:
-            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          # Note: environment must be specified at BOTH job level, and input to publish action
-          environment: production
-          steps:
-            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+    name: "PyPI release"
+    # yamllint disable-line rule:line-length
+    if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[release]')
+    needs:
+      - repository
+      - pypi-test
+    runs-on: "ubuntu-24.04"
+    permissions:
+      contents: read
+      # Needed for trusted publishing; must also be passed from parent workflows
+      id-token: write
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    # Note: environment must be specified at BOTH job level, and input to publish action
+    environment: production
+    steps:
+      # Need repository content to extract project name
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-            - name: "Release to PyPI"
-              # yamllint disable-line rule:line-length
-              uses: ./.github/actions/pypi-publish-action # Local copy of upstream 2025-02-25
-              env:
-                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              with:
-                environment: production
-                tag: ${{ needs.repository.outputs.build_tag }}
-                # yamllint disable-line rule:line-length
-                one_password_item: "op://hdiyadcjno2knqgvcy4wj5ulya/vds5rebqxeqfrjqwpszxxicmzq/password"
-                op_service_account_token: ${{ secrets.ONE_PASSWORD_PRODUCTION }}
-                pypi_credential: ${{ secrets.PYPI_PRODUCTION }}
-                attestations: "true"
+      - name: "Extract project/repository naming"
+        id: naming
+        # yamllint disable-line rule:line-length
+        uses: lfit/releng-reusable-workflows/.github/actions/python-project-name-action@431c4e424c15544f98ec1321f6668f655c238d3a # 2025-02-10
+
+      - name: "⬇ Download build artefacts"
+        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+        with:
+          name: ${{ steps.naming.outputs.python_project_name }}
+          path: "dist"
+
+      - name: "Remove unsupported artefact file types"
+        shell: bash
+        run: |
+          # Remove unsupported artefact file types
+          find . ! -name '*.whl' ! -name '*.tar.gz' -type f -exec rm -f {} + || true
+
+      - name: "Checking package index for build/release"
+        id: check-remote
+        # yamllint disable-line rule:line-length
+        uses: os-climate/osc-github-devops/.github/actions/pypi-version-check-action@50987892d52819798d74f5b381d3abfb8d54cbf0 # 2025-03-03
+        with:
+          package_name: ${{ steps.naming.outputs.python_project_name }}
+          package_version: ${{ needs.repository.outputs.build_tag }}
+          environment: "production"
+
+      - name: "Publish PyPI [Trusted Publishing]"
+        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
+        # yamllint disable-line rule:line-length
+        with:
+          # We already validated earlier in the pipeline (twine)
+          verify-metadata: false
+          attestations: true
+          # Show checksum values
+          print-hash: true
+          # Optional debugging, pretty much essential for information on failures
+          verbose: true
 
   github-release:
     name: "GitHub release"
@@ -177,7 +229,7 @@ jobs:
     steps:
       - name: "GitHub Release"
         # yamllint disable-line rule:line-length
-        uses: os-climate/osc-github-devops/.github/actions/github-release-action@e40c93a51cc32cbddd4767a75e2209af971df9e0 # 2025-02-25
+        uses: os-climate/osc-github-devops/.github/actions/github-release-action@45cee44c1a0bfdc8e64f94cf32c833ef61f95a50 # 2025-02-25
         with:
           project_name: ${{ env.python_project_name }}
           artefact_path: "dist"
